### ISSUE TITLE
npm@10 not supported?

### ISSUE THREAD

**Issue by Steppico** [tool-belt/interface-forge#38]
Hi there,

I'm trying to install the latest version of `interface-forge` on my project but I ran in the following issue:
```bash
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: interface-forge@2.0.0
npm ERR! notsup Not compatible with your version of node/npm: interface-forge@2.0.0
npm ERR! notsup Required: {"yarn":"please-use-pnpm","npm":"please-use-pnpm","pnpm":">=8.0.0","node":">=21.0.0"}
npm ERR! notsup Actual:   {"npm":"10.2.4","node":"v20.11.1"}
```

I solved by reverting the library to `v1.6.1` but was also wondering if there's any plan on supporting new npm versions in the future (I imagine not, given the message asking to use `pnpm`... but still asking 🙏 )

**Comment by Goldziher** [comment]
Oh, this shouldn't be happening on your end. Clearly a bug. I'll fix it today. You're welcome to submit a pr if you want to fix this as well.
